// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/jiebutech/datasource"
	"github.com/jiebutech/zin/app/api"
	"github.com/jiebutech/zin/app/repo"
	"github.com/jiebutech/zin/app/service"
)

// Injectors from wire.go:

func NewDemoController(orm *datasource.Orm) *api.DemoCtrl {
	demoRepo := repo.NewDemoRepo(orm)
	demoSvc := service.NewDemoSvc(demoRepo)
	demoCtrl := api.NewDemoCtrl(demoSvc)
	return demoCtrl
}
